# Generated by Django 2.1.7 on 2019-02-22 14:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0006_auto_20190222_1133'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glosa', models.CharField(max_length=40)),
                ('fecha_ingreso', models.DateTimeField(default=datetime.datetime(2019, 2, 22, 11, 33, 56, 419066))),
                ('monto', models.IntegerField()),
                ('estado', models.CharField(choices=[('Vendida', 'Vendida'), ('Pendiente', 'Pendiente'), ('Desierta', 'Desierta')], max_length=30)),
                ('demandante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Demandante')),
                ('productos', models.ManyToManyField(to='producto.Producto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
