# Generated by Django 2.1.7 on 2019-02-22 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_auto_20190222_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 13, 31, 16, 211311)),
        ),
        migrations.AlterField(
            model_name='historia_cotizacion',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 13, 31, 16, 211311)),
        ),
    ]
