# Generated by Django 2.1.7 on 2019-02-15 02:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizacion', '0001_initial'),
        ('cliente', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demandante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_demandante', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateTimeField(default=datetime.datetime(2019, 2, 14, 23, 35, 21, 863383))),
                ('direccion_demandante', models.CharField(blank=True, max_length=50)),
                ('correo_demandante', models.EmailField(blank=True, max_length=50)),
                ('telefono_demandante', models.CharField(blank=True, max_length=50)),
                ('comuna_demandante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localizacion.Comuna_Chile')),
                ('dependencia_demandante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Dependencia')),
                ('id_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('region_demandante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localizacion.Region_Chile')),
            ],
        ),
    ]
