# Generated by Django 2.1.7 on 2019-02-16 20:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_demandante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='giro_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Giro_Cliente'),
        ),
        migrations.AlterField(
            model_name='demandante',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 16, 17, 32, 32, 897778)),
        ),
    ]
