# Generated by Django 2.1.7 on 2019-02-22 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20190216_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandante',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 11, 27, 51, 207466)),
        ),
    ]
