# Generated by Django 2.1.7 on 2019-02-22 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20190222_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandante',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 11, 50, 10, 666045)),
        ),
    ]
