# Generated by Django 2.1.7 on 2019-02-15 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna_Chile',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia_Chile',
            fields=[
                ('id_provincia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region_Chile',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=50)),
                ('ISO_3166_2_CL', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='provincia_chile',
            name='id_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localizacion.Region_Chile'),
        ),
        migrations.AddField(
            model_name='comuna_chile',
            name='id_provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localizacion.Provincia_Chile'),
        ),
    ]
